name: app1
description: Application 1.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  common:
    path: ../common/
  flutter:
    sdk: flutter
  envied: ^0.3.0+3
  envied_generator: ^0.3.0+3
  retrofit: ">=4.0.0 <5.0.0"
  dio: ^5.3.2
  injectable: ^2.1.2
  get_it: ^7.6.0
  logger: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ">=2.3.0 <4.0.0"
  flutter_lints: ^2.0.0
  retrofit_generator: ">=5.0.0 <6.0.0"
  injectable_generator: ^2.1.6

flutter:
  uses-material-design: true
