name: common
description: common ui and logic.
version: 1.0.0

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  retrofit: ">=4.0.0 <5.0.0"
  logger: ^2.0.1
  dio: ^5.3.2
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  retrofit_generator: ">=5.0.0 <6.0.0"
  build_runner: ">=2.3.0 <4.0.0"

flutter:
  uses-material-design: true
